# Generated by Django 4.1.5 on 2023-05-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='samples',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
