# Generated by Django 4.1.5 on 2023-01-30 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_alter_company_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateTimeField(auto_created=True)),
                ('project_name', models.CharField(max_length=200)),
                ('project_po', models.CharField(max_length=5)),
                ('date_initiated', models.DateField()),
                ('date_updated', models.DateField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.company')),
            ],
        ),
    ]
