# Generated by Django 4.1.5 on 2023-05-09 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200)),
                ('project_po', models.CharField(max_length=5)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('date_initiated', models.DateField(blank=True, null=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('project_status', models.IntegerField(choices=[(1, 'Created'), (2, 'Testing'), (3, 'Completed')], default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.company')),
            ],
        ),
    ]
