# Generated by Django 4.1.5 on 2023-05-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_alter_samples_sample_status'),
        ('projects', '0004_alter_projects_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_samples',
            field=models.ManyToManyField(related_name='project_samples', to='samples.samples'),
        ),
    ]
