version: '3.8'

services:
  web:
    build: ./microLIMS
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./microLIMS/:/app
    ports:
      - "8000:8000"
    env_file:
      - ./microLIMS/.env

