# Generated by Django 4.1.5 on 2023-05-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('samples', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_samples',
            field=models.ManyToManyField(to='samples.samples'),
        ),
    ]
