# Generated by Django 4.1.5 on 2023-05-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projects_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_status',
            field=models.IntegerField(choices=[(1, 'Created'), (2, 'Testing'), (3, 'Completed'), (4, 'Cancelled')], default=1),
        ),
    ]
