# Generated by Django 3.2.7 on 2021-10-31 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='customer_contact',
            field=models.CharField(default='NA', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, default='update needed', max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'/", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
