# Generated by Django 4.1.5 on 2023-05-12 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_company_customer_contact'),
        ('test_methods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customers.company'),
            preserve_default=False,
        ),
    ]
