# Generated by Django 4.1.5 on 2023-05-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_methods', '0002_test_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_status',
            field=models.IntegerField(choices=[(1, 'Created'), (2, 'Testing'), (3, 'Completed'), (4, 'Cancelled')], default=1),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.IntegerField(choices=[(1, 'QUANTITATIVE'), (2, 'QUALITATIVE')], default=1),
        ),
    ]
