# Generated by Django 3.2.7 on 2021-10-23 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=20)),
                ('test_code', models.CharField(max_length=10)),
                ('testMethod', models.CharField(max_length=20)),
                ('test_type', models.CharField(choices=[('QUANTITATIVE', 'Quantitative'), ('QUALITATIVE', 'Qualitative')], default='Qualitative', max_length=12)),
            ],
        ),
    ]
