# Generated by Django 4.1.5 on 2023-05-15 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_alter_samples_sample_status'),
        ('test_methods', '0003_test_test_status_alter_test_test_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='company',
        ),
        migrations.RemoveField(
            model_name='test',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test_status',
        ),
        migrations.CreateModel(
            name='Sample_Testing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_status', models.IntegerField(choices=[(1, 'Created'), (2, 'Testing'), (3, 'Completed'), (4, 'Cancelled')], default=1)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.samples')),
                ('testing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_methods.test')),
            ],
        ),
    ]
