# Generated by Django 4.1.5 on 2023-05-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_methods', '0004_remove_test_company_remove_test_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
