# Generated by Django 3.2.7 on 2021-10-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('phone', models.CharField(max_length=12)),
                ('entity', models.CharField(choices=[('CUSTOMER', 'Customer'), ('INTERNAL', 'Internal')], default='Customer', max_length=9)),
            ],
        ),
    ]
