# Generated by Django 4.1.5 on 2023-05-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_company_customer_contact_alter_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='customer_contact',
            field=models.CharField(max_length=200),
        ),
    ]
