# Generated by Django 4.1.5 on 2023-05-09 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_methods', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='samples',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sample_name', models.CharField(max_length=15)),
                ('sample_description', models.CharField(max_length=100)),
                ('sample_created', models.DateTimeField(auto_now_add=True)),
                ('testing_started', models.DateField(blank=True, null=True)),
                ('testing_completed', models.DateField(blank=True, null=True)),
                ('sample_status', models.IntegerField(choices=[(1, 'Created'), (2, 'Testing'), (3, 'Completed')], default=1)),
                ('analysis', models.ManyToManyField(to='test_methods.test')),
                ('sample_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects')),
            ],
        ),
    ]
