# Generated by Django 4.1.5 on 2023-01-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_methods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='samples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_created', models.DateTimeField(auto_created=True)),
                ('sample_name', models.CharField(max_length=15)),
                ('sample_description', models.CharField(max_length=100)),
                ('analysis', models.ManyToManyField(to='test_methods.test')),
            ],
        ),
    ]
